### PR TITLE
Laravel 7 support

### PR DESCRIPTION
**Pull request by damiani**
Updates version constraints on Illuminate dependencies to support Laravel version 7.

### CODE REVIEW

**Comment by jorisatabix** [comment]
@arrilot Could you have a look at this PR?

**Comment by brysem** [comment]
I would like to see this merged. Is this repository still maintained? If not, we can get a fork started. It would be a shame not to be able to use such a wonderful package.

**Comment by jorisatabix** [comment]
Forked this package and it's available here for laravel 7: https://packagist.org/packages/atabix/laravel-data-anonymization

**Comment by arrilot** [comment]
Sorry for completely missing this. Merged

**Comment by arrilot** [comment]
You can grab fresh 1.2.0 release with this changes

**Comment by brysem** [comment]
Awesome. Thank you very much!

**Pull request merged**
